init:
- whoami
- appveyor version
#- freebsd-version
- bash --version
- dotnet --version
- pwd
- env

test_script:
- ps -aux
- bash enable-ssh.sh
#- ls -al ~/build-agent
- ls -al ~/projects

artifacts:
- path: README.md

build: off
