init:
- whoami
- appveyor version
- freebsd-version
- bash --version
- dotnet --version
- pwd
- env
#- ls -al /etc/ssh
#- sudo ssh-keygen -A
#- ls -al /etc/ssh
#- sudo service sshd start
#- sleep 60
- sockstat -l
- bash enable-ssh.sh

test_script:
#- ls -al ~/build-agent
- ls -al ~/projects

artifacts:
- path: README.md

build: off
