init:
- whoami
- appveyor version
- freebsd-version
- bash --version
- dotnet --version
- pwd
- env
- cat /etc/rc.conf
#- sudo ipfw -q -f flush
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -

test_script:
#- ls -al ~/build-agent
- ls -al ~/projects

artifacts:
- path: README.md

build: off
