init:
- whoami
- appveyor version
#- freebsd-version
- bash --version
- dotnet --version
- pwd
- env

test_script:
#- sudo ufw disable
#- sudo ufw status verbose
#- sudo ufw --force reset
- sudo ufw status verbose
- bash enable-ssh.sh
#- ls -al ~/build-agent
- ls -al ~/projects

artifacts:
- path: README.md

build: off
