init:
- who am i
#- tty
- appveyor version
#- freebsd-version
- bash --version
- dotnet --version
- pwd
- export -p

test_script:
#- sudo lsof -i -P -n | grep LISTEN
- ls -alG /usr/bin
- dotnet dd
- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
#- ls -al ~/build-agent
#- ls -al ~/projects

artifacts:
- path: README.md

build: off
